name: CI build

on: workflow_dispatch

jobs:

  build:
    name: build arm platflom
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    #- uses: actions/cache@v3
    #  with:
    #    path: |
    #      ~/.gradle/caches
    #      ~/.gradle/wrapper
    #    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'gradle'

    - name: building
      run: |
        chmod a+x gradlew
        ./gradlew build

    - uses: actions/upload-artifact@v3
      with:
        name: debug-archive.zip
        path: |
          app/build/**/*.apk
          ~/app/**/*.apk
